apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: axis-backend

build:
  hooks:
    before:
      - command: ["./gradlew", "build", "-x", "test"]
  artifacts:
    - image: axis/goal
      context: .
      docker:
        dockerfile: axis-goal/src/main/docker/Dockerfile.jvm
    - image: axis/media
      context: .
      docker:
        dockerfile: axis-media/src/main/docker/Dockerfile.jvm
    - image: axis/notification
      context: .
      docker:
        dockerfile: axis-notification/src/main/docker/Dockerfile.jvm
    - image: axis/user
      context: .
      docker:
        dockerfile: axis-user/src/main/docker/Dockerfile.jvm
  local:
    push: false

manifests:
  rawYaml:
    - k8s/namespace.yaml
    - k8s/config/**
    - k8s/infrastructure/**
    - k8s/gateway-api.yaml
    - k8s/axis-goal.yaml
    - k8s/axis-media.yaml
    - k8s/axis-notification.yaml
    - k8s/axis-user.yaml

deploy:
  kubectl: {}

portForward:
  - resourceType: service
    resourceName: nginx-gateway
    namespace: nginx-gateway
    port: 80
    localPort: 8080
    address: 0.0.0.0
  - resourceType: service
    resourceName: rabbitmq
    namespace: axis
    port: 15672
    localPort: 15672
    address: 0.0.0.0
  - resourceType: service
    resourceName: postgres-app
    namespace: axis
    port: 5432
    localPort: 5433
  - resourceType: service
    resourceName: mongodb
    namespace: axis
    port: 27017
    localPort: 27017
  - resourceType: service
    resourceName: prometheus
    namespace: axis
    port: 9090
    localPort: 9090
    address: 0.0.0.0
  - resourceType: service
    resourceName: grafana
    namespace: axis
    port: 3000
    localPort: 3000
    address: 0.0.0.0
