apiVersion: skaffold/v2beta2
kind: Config
metadata:
  name: axis-backend

build:
  artifacts:
    - image: axis/goal
      context: .
      jib:
        project: axis-goal
        type: gradle
    - image: axis/media
      context: .
      jib:
        project: axis-media
        type: gradle
    - image: axis/notification
      context: .
      jib:
        project: axis-notification
        type: gradle
  local:
    push: false
    useBuildkit: true

deploy:
  kustomize:
    paths:
      - k8s/overlays/jvm

portForward:
  - resourceType: service
    resourceName: axis-gateway-nginx
    namespace: axis
    port: 80
    localPort: 8080
  - resourceType: service
    resourceName: keycloak
    namespace: axis
    port: 8080
    localPort: 8180
  - resourceType: service
    resourceName: rabbitmq
    namespace: axis
    port: 15672
    localPort: 15672
  - resourceType: service
    resourceName: postgres-app
    namespace: axis
    port: 5432
    localPort: 5433
  - resourceType: service
    resourceName: mongodb
    namespace: axis
    port: 27017
    localPort: 27017
  - resourceType: service
    resourceName: redis
    namespace: axis
    port: 6379
    localPort: 6379

profiles:
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
        - image: axis/goal
          context: .
          jib:
            project: axis-goal
            type: gradle
            args: ["--no-daemon"]
        - image: axis/media
          context: .
          jib:
            project: axis-media
            type: gradle
            args: ["--no-daemon"]
        - image: axis/notification
          context: .
          jib:
            project: axis-notification
            type: gradle
            args: ["--no-daemon"]

  - name: native
    build:
      artifacts:
        - image: axis/goal-native
          context: .
          custom:
            buildCommand: ./gradlew :axis-goal:bootBuildImage --imageName=axis/goal-native
        - image: axis/media-native
          context: .
          custom:
            buildCommand: ./gradlew :axis-media:bootBuildImage --imageName=axis/media-native
        - image: axis/notification-native
          context: .
          custom:
            buildCommand: ./gradlew :axis-notification:bootBuildImage --imageName=axis/notification-native
    deploy:
      kustomize:
        paths:
          - k8s/overlays/native