apiVersion: skaffold/v2beta2
kind: Config
metadata:
  name: axis-backend

build:
  artifacts:
    - image: axis/gateway
      context: .
      jib:
        project: axis-gateway
        type: gradle
    - image: axis/media
      context: .
      jib:
        project: axis-media
        type: gradle
  local:
    push: false
    useBuildkit: true

deploy:
  kubectl:
    manifests:
      - k8s/namespace.yaml
      - k8s/config/configmaps.yaml
      - k8s/config/secrets.yaml
      - k8s/infrastructure/postgres-keycloak.yaml
      - k8s/infrastructure/postgres-app.yaml
      - k8s/infrastructure/keycloak.yaml
      - k8s/infrastructure/mongodb.yaml
      - k8s/infrastructure/rabbitmq.yaml
      - k8s/infrastructure/redis.yaml
      - k8s/infrastructure/keycloak-realm-config.yaml
      - k8s/services/axis-gateway.yaml
      - k8s/services/axis-media.yaml

portForward:
  - resourceType: service
    resourceName: axis-gateway
    namespace: axis
    port: 8080
    localPort: 8080
  - resourceType: service
    resourceName: keycloak
    namespace: axis
    port: 8080
    localPort: 8180
  - resourceType: service
    resourceName: rabbitmq
    namespace: axis
    port: 15672
    localPort: 15672
  - resourceType: service
    resourceName: postgres-app
    namespace: axis
    port: 5432
    localPort: 5433
  - resourceType: service
    resourceName: postgres-keycloak
    namespace: axis
    port: 5432
    localPort: 5434
  - resourceType: service
    resourceName: mongodb
    namespace: axis
    port: 27017
    localPort: 27017
  - resourceType: service
    resourceName: redis
    namespace: axis
    port: 6379
    localPort: 6379

profiles:
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
        - image: axis/gateway
          context: .
          jib:
            project: axis-gateway
            type: gradle
            args: ["--no-daemon"]
        - image: axis/media
          context: .
          jib:
            project: axis-media
            type: gradle
            args: ["--no-daemon"]