apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: axis-backend

build:
  artifacts:
    - image: axis/goal
      context: .
      docker:
        dockerfile: axis-goal/src/main/docker/Dockerfile.jvm
      hooks:
        before:
          - command: ["./gradlew", ":axis-goal:build", "-x", "test"]
    - image: axis/media
      context: .
      docker:
        dockerfile: axis-media/src/main/docker/Dockerfile.jvm
      hooks:
        before:
          - command: ["./gradlew", ":axis-media:build", "-x", "test"]
    - image: axis/notification
      context: .
      docker:
        dockerfile: axis-notification/src/main/docker/Dockerfile.jvm
      hooks:
        before:
          - command: ["./gradlew", ":axis-notification:build", "-x", "test"]
  local:
    push: false

deploy:
  kubectl:
    manifests:
      - k8s/namespace.yaml
      - k8s/config/**
      - k8s/infrastructure/**
      - k8s/*.yaml

portForward:
  - resourceType: service
    resourceName: nginx-gateway
    namespace: nginx-gateway
    port: 80
    localPort: 8080
  - resourceType: service
    resourceName: rabbitmq
    namespace: axis
    port: 15672
    localPort: 15672
  - resourceType: service
    resourceName: postgres-app
    namespace: axis
    port: 5432
    localPort: 5433
  - resourceType: service
    resourceName: mongodb
    namespace: axis
    port: 27017
    localPort: 27017
  - resourceType: service
    resourceName: redis
    namespace: axis
    port: 6379
    localPort: 6379
