apiVersion: v1
kind: Secret
metadata:
  name: postgres-app-secret
  namespace: axis
type: Opaque
stringData:
  POSTGRES_PASSWORD: axis_password
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: axis
type: Opaque
stringData:
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
  KC_DB_PASSWORD: axis_password
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: axis
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: axis_admin
  MONGO_INITDB_ROOT_PASSWORD: mongo_password
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: axis
type: Opaque
stringData:
  RABBITMQ_DEFAULT_PASS: rabbitmq_password
  RABBITMQ_ERLANG_COOKIE: secret_cookie_value
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: axis
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: admin
