package com.axis.notification.mapper;

import com.axis.notification.model.dto.NotificationTemplateRequest;
import com.axis.notification.model.dto.NotificationTemplateResponse;
import com.axis.notification.model.entity.NotificationTemplates;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;

@Mapper(componentModel = "cdi")
public interface NotificationTemplatesMapper {

    /**
     * Convert request DTO to entity
     * ID is generated by the database
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    NotificationTemplates toEntity(NotificationTemplateRequest request);

    /**
     * Convert entity to response DTO
     */
    NotificationTemplateResponse toResponse(NotificationTemplates entity);

    /**
     * Update existing entity from request DTO
     * ID and timestamps are preserved
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    void updateEntity(NotificationTemplateRequest request, @MappingTarget NotificationTemplates entity);
}