####
# This Dockerfile is used to build a native executable for axis-goal
####
FROM quay.io/quarkus/quarkus-micro-image:2.0
WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root build/*-runner /work/application

EXPOSE 8081
USER 1001

ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]
